apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_HOST: "{{ .Release.Name }}-postgres-service"
  POSTGRES_PORT: "5432"
  DEBUG: {{ .Values.django.debug | quote }}
  ALLOWED_HOSTS: {{ .Values.django.allowed_hosts | quote }}
  OLLAMA_HOST: {{ .Values.django.ollama_host | quote }}
  VITE_API_BASE_URL: {{ .Values.frontendConfig.apiBaseUrl | quote }}
